services:
  - type: web
    name: textguard-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.6"
    disk:
      name: model-weights
      mountPath: /opt/render/project/src/models/weights
      sizeGB: 1
